export const SET_POKEMONS = "SET_POKEMONS";
export const SET_LOADING = "SET_LOADING";
export const SET_FAVORITE = "SET_FAVORITE";
export const SET_POKEBOLA = "SET_POKEBOLA";
export const SET_POKEBOLA_DELETE = "SET_POKEBOLA_DELETE"


// export const SET_POKEMONS_REQUEST = "SET_POKEMONS_REQUEST";
// export const SET_POKEMONS_SUCCESS = "SET_POKEMONS_SUCCESS";
// export const SET_POKEMONS_FAILURE = "SET_POKEMONS_FAILURE";
// export const SET_POKEMONS_FULFILL = "SET_POKEMONS_FULFILL";